spring:
  security:
    oauth2:
      authorizationserver:
        client:
          a:
            registration:
              clientAuthenticationMethods:
                - client_secret_basic
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              clientId: a
              clientSecret: b
      client:
        registration:
          my-client:
            provider: github
            client-id: 72d14697d88b080669ad
            client-secret: 845d94d2034a9488232af08875e194a85e7a7b6b
            scope:
              - openid
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/token
            user-info-uri: https://github.com/login/oauth/userinfo
            jwk-set-uri: https://github.com/login/oauth/keys
#            user-name-attribute: sub
logging:
  level:
    org.springframework: trace
