spring:
  security:
    oauth2:
      # noinspection SpellCheckingInspection
      authorizationserver:
        client:
          a:
            require-proof-key: true
            registration:
              clientAuthenticationMethods:
                - none
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8081"
              clientId: a
              clientSecret: b
      client:
        registration:
          github-idp:
            provider: github
            client-id: 72d14697d88b080669ad
            client-secret: 845d94d2034a9488232af08875e194a85e7a7b6b
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
