spring:
  security:
    oauth2:
      authorizationserver:
        client:
          a:
            registration:
              clientAuthenticationMethods:
                - client_secret_basic
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              clientId: a
              clientSecret: b
      client:
        registration:
          github-idp:
            provider: github
            client-id: 72d14697d88b080669ad
            client-secret: 845d94d2034a9488232af08875e194a85e7a7b6b
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login

#logging:
#  level:
#    org.springframework: trace
